app/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)

    from app.blueprints.admin import admin

    app.register_blueprint(admin)

    from app.blueprints.main import main

    app.register_blueprint(main)

    return app

app/blueprints/admin.py
from flask import Blueprint, render_template

admin = Blueprint("admin", __name__, url_prefix="/admin")


@admin.route("/dashboard")
def dashboard():
    return render_template("/dashboard/index.html")

app/blueprints/main.py
from flask import Blueprint, render_template

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template("main/index.html")

app/templates/base/dashboard_base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='img/python.svg')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Flask - {% block title %}Main{%endblock%}</title>
</head>

<body>
    {% include 'base/layouts/navbar.html' %}
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    {% include 'base/layouts/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/base/layouts/footer.html
<footer>
    <footer class="bg-dark text-light py-1 fixed-bottom">
        <div class="text-center">
            <p>Estructura para proyecto en Flask © 2025</p>
        </div>
    </footer>
</footer>

app/templates/base/layouts/navbar.html
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/python.svg')}}" alt="Logo" width="30" height="24"
                class="d-inline-block align-text-top">
            Navbar
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('admin.dashboard') }}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 2</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Menu
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Opcion 1</a></li>
                        <li><a class="dropdown-item" href="#">Opcion 2</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Opcion 3</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/templates/base/main_base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='img/python.svg')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Flask - {% block title %}Main{%endblock%}</title>
</head>

<body>
    <div class="container">
        {% block content %}

        {% endblock %}
        {% include 'base/layouts/footer.html' %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</body>

</html>

app/templates/dashboard/index.html
{% extends 'base/dashboard_base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="text-center mt-5">
    <h1>Dashboard</h1>
    <a href="{{ url_for('main.index') }}" class="btn btn-danger">Salir</a>

</div>
{% endblock %}

app/templates/main/index.html
{% extends 'base/main_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="text-center mt-5">
    <h1>Home</h1>
    <p>Welcome to the home page!</p>
    <a href="{{ url_for('admin.dashboard') }}" class="btn btn-dark">Entrar</a>

</div>
{% endblock %}